--------------------------------------------------------
--  File created - poniedzia³ek-maja-18-2020   
--------------------------------------------------------
DROP SEQUENCE "PK"."KONTO_SEQ";
DROP TABLE "PK"."AUTORZY";
DROP TABLE "PK"."BUDYNEK";
DROP TABLE "PK"."GRUPA_STUDENTOW";
DROP TABLE "PK"."KONTO";
DROP TABLE "PK"."LOGIN";
DROP TABLE "PK"."PUBLIKACJA";
DROP TABLE "PK"."SALA";
DROP TABLE "PK"."STATUS_TASKA";
DROP TABLE "PK"."TASK";
DROP TABLE "PK"."TYP_KONTA";
DROP TABLE "PK"."WAGA_ZADANIA";
DROP TABLE "PK"."ZADANIE";
DROP TABLE "PK"."ZAJECIE";
--------------------------------------------------------
--  DDL for Sequence KONTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PK"."KONTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table AUTORZY
--------------------------------------------------------

  CREATE TABLE "PK"."AUTORZY" 
   (	"ID_AUTORA" NUMBER(3,0), 
	"ID_KONTA" NUMBER(3,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BUDYNEK
--------------------------------------------------------

  CREATE TABLE "PK"."BUDYNEK" 
   (	"ID_BUDYNKU" NUMBER(5,0), 
	"NAZWA_BUDYNKU" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GRUPA_STUDENTOW
--------------------------------------------------------

  CREATE TABLE "PK"."GRUPA_STUDENTOW" 
   (	"ID_GRUPY" NUMBER(5,0), 
	"ILOSC_OSOB" NUMBER(5,0), 
	"SPECJALIZACJA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KONTO
--------------------------------------------------------

  CREATE TABLE "PK"."KONTO" 
   (	"ID_KONTA" NUMBER(3,0), 
	"TYTUL" VARCHAR2(50 BYTE), 
	"IMIE" VARCHAR2(20 BYTE), 
	"NAZWISKO" VARCHAR2(20 BYTE), 
	"ID_TYPU_KONTA" NUMBER(2,0), 
	"SPECJALIZACJA" VARCHAR2(30 BYTE), 
	"IMAGE" VARCHAR2(24 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "PK"."LOGIN" 
   (	"ID_KONTA" NUMBER(5,0), 
	"LOGIN" VARCHAR2(25 BYTE), 
	"HASLO" VARCHAR2(24 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PUBLIKACJA
--------------------------------------------------------

  CREATE TABLE "PK"."PUBLIKACJA" 
   (	"ID_PUBLIKACJI" NUMBER(4,0), 
	"ID_AUTORA" NUMBER(3,0), 
	"TYTUL_PUBLIKACJI" VARCHAR2(100 BYTE), 
	"DATA_PUBLIKACJI" DATE, 
	"ISBN" NUMBER(13,0), 
	"MIESJCE_WYSTAPIENIA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALA
--------------------------------------------------------

  CREATE TABLE "PK"."SALA" 
   (	"ID_SALI" NUMBER(5,0), 
	"ID_BUDYNKU" NUMBER(5,0), 
	"NR_SALI" NUMBER(5,0), 
	"TYP_SALI" VARCHAR2(10 BYTE), 
	"MAX_OS" NUMBER(3,0), 
	"WYPOSAZENIE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATUS_TASKA
--------------------------------------------------------

  CREATE TABLE "PK"."STATUS_TASKA" 
   (	"ID_STATUSU_TASKA" NUMBER(2,0), 
	"NAZWA_STATUSU" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TASK
--------------------------------------------------------

  CREATE TABLE "PK"."TASK" 
   (	"ID_TASKA" NUMBER(6,0), 
	"DATA_UTWORZENIA" DATE, 
	"CZAS_REALIZACJI" DATE, 
	"TYTUL_TASKA" VARCHAR2(50 BYTE), 
	"TRESC" VARCHAR2(500 BYTE), 
	"ID_STATUSU_TASKA" NUMBER(2,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TYP_KONTA
--------------------------------------------------------

  CREATE TABLE "PK"."TYP_KONTA" 
   (	"ID_TYPU_KONTA" NUMBER(3,0), 
	"NAZWA_TYPU_KONTA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WAGA_ZADANIA
--------------------------------------------------------

  CREATE TABLE "PK"."WAGA_ZADANIA" 
   (	"ID_WAGI_ZADANIA" NUMBER(5,0), 
	"WAGA" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZADANIE
--------------------------------------------------------

  CREATE TABLE "PK"."ZADANIE" 
   (	"ID_ZADANIA" NUMBER(6,0), 
	"ID_KONTA" NUMBER(3,0), 
	"ID_TASKA" NUMBER(6,0), 
	"ID_WAGI_ZADANIA" VARCHAR2(10 BYTE) DEFAULT 'NORMAL'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZAJECIE
--------------------------------------------------------

  CREATE TABLE "PK"."ZAJECIE" 
   (	"ID_ZAJECIA" NUMBER(5,0), 
	"ID_GRUPY" NUMBER(5,0), 
	"ID_KONTA" NUMBER(5,0), 
	"ID_SALI" NUMBER(5,0), 
	"SPECJALIZACJA" VARCHAR2(24 BYTE), 
	"LICZBA_GODZIN" NUMBER(5,0), 
	"DZIEN_TYGODNIA" VARCHAR2(10 BYTE), 
	"GODZINA_ROZPOCZECIA" NUMBER(4,0), 
	"WYPOSAZENIE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into PK.AUTORZY
SET DEFINE OFF;
REM INSERTING into PK.BUDYNEK
SET DEFINE OFF;
REM INSERTING into PK.GRUPA_STUDENTOW
SET DEFINE OFF;
REM INSERTING into PK.KONTO
SET DEFINE OFF;
Insert into PK.KONTO (ID_KONTA,TYTUL,IMIE,NAZWISKO,ID_TYPU_KONTA,SPECJALIZACJA,IMAGE) values ('1','dr.hab.mgr.inz','Adam','Spec','1','Informatyka',null);
Insert into PK.KONTO (ID_KONTA,TYTUL,IMIE,NAZWISKO,ID_TYPU_KONTA,SPECJALIZACJA,IMAGE) values ('2','dr.','Maciej','Nowak','2','Elektryk',null);
Insert into PK.KONTO (ID_KONTA,TYTUL,IMIE,NAZWISKO,ID_TYPU_KONTA,SPECJALIZACJA,IMAGE) values ('3','mgr.inz','Marcin','Kowalski','2','Mechatronik',null);
Insert into PK.KONTO (ID_KONTA,TYTUL,IMIE,NAZWISKO,ID_TYPU_KONTA,SPECJALIZACJA,IMAGE) values ('4','dr.','Adam','Maysz','3','Fizyka',null);
Insert into PK.KONTO (ID_KONTA,TYTUL,IMIE,NAZWISKO,ID_TYPU_KONTA,SPECJALIZACJA,IMAGE) values ('7','dr.','Boguslaw','Linda','2','Automatyka i Robotyka',null);
Insert into PK.KONTO (ID_KONTA,TYTUL,IMIE,NAZWISKO,ID_TYPU_KONTA,SPECJALIZACJA,IMAGE) values ('6','mgr.inz','Hubert','Pietrzak','3','Informatyka',null);
Insert into PK.KONTO (ID_KONTA,TYTUL,IMIE,NAZWISKO,ID_TYPU_KONTA,SPECJALIZACJA,IMAGE) values ('5','dr.hab.','Robert','Kubica','3','Mechanika',null);
Insert into PK.KONTO (ID_KONTA,TYTUL,IMIE,NAZWISKO,ID_TYPU_KONTA,SPECJALIZACJA,IMAGE) values ('8','mgr.inz','Patryk','Vega','2','Informatyka',null);
Insert into PK.KONTO (ID_KONTA,TYTUL,IMIE,NAZWISKO,ID_TYPU_KONTA,SPECJALIZACJA,IMAGE) values ('9','dr.hab.mgr.inz','Justyna','Kowalczyk','2','Budowa Maszyn',null);
Insert into PK.KONTO (ID_KONTA,TYTUL,IMIE,NAZWISKO,ID_TYPU_KONTA,SPECJALIZACJA,IMAGE) values ('10','mgr.inz','Krystyna','Czubówna','3','Bio-technologie',null);
REM INSERTING into PK.LOGIN
SET DEFINE OFF;
Insert into PK.LOGIN (ID_KONTA,LOGIN,HASLO) values ('1','111111@edu.p.lodz.pl','pk12345!');
Insert into PK.LOGIN (ID_KONTA,LOGIN,HASLO) values ('2','111112@edu.p.lodz.pl','pk12345!');
Insert into PK.LOGIN (ID_KONTA,LOGIN,HASLO) values ('3','111113@edu.p.lodz.pl','pk12345!');
Insert into PK.LOGIN (ID_KONTA,LOGIN,HASLO) values ('4','111114@edu.p.lodz.pl','pk12345!');
Insert into PK.LOGIN (ID_KONTA,LOGIN,HASLO) values ('5','111115@edu.p.lodz.pl','pk12345!');
Insert into PK.LOGIN (ID_KONTA,LOGIN,HASLO) values ('6','111116@edu.p.lodz.pl','pk12345!');
Insert into PK.LOGIN (ID_KONTA,LOGIN,HASLO) values ('7','111117@edu.p.lodz.pl','pk12345!');
Insert into PK.LOGIN (ID_KONTA,LOGIN,HASLO) values ('8','111118@edu.p.lodz.pl','pk12345!');
Insert into PK.LOGIN (ID_KONTA,LOGIN,HASLO) values ('9','111119@edu.p.lodz.pl','pk12345!');
Insert into PK.LOGIN (ID_KONTA,LOGIN,HASLO) values ('10','111110@edu.p.lodz.pl','pk12345!');
REM INSERTING into PK.PUBLIKACJA
SET DEFINE OFF;
REM INSERTING into PK.SALA
SET DEFINE OFF;
REM INSERTING into PK.STATUS_TASKA
SET DEFINE OFF;
REM INSERTING into PK.TASK
SET DEFINE OFF;
REM INSERTING into PK.TYP_KONTA
SET DEFINE OFF;
REM INSERTING into PK.WAGA_ZADANIA
SET DEFINE OFF;
REM INSERTING into PK.ZADANIE
SET DEFINE OFF;
REM INSERTING into PK.ZAJECIE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index AUTORZY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK"."AUTORZY_PK" ON "PK"."AUTORZY" ("ID_AUTORA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_BUDYNKU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK"."ID_BUDYNKU_PK" ON "PK"."BUDYNEK" ("ID_BUDYNKU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_GRUPY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK"."ID_GRUPY_PK" ON "PK"."GRUPA_STUDENTOW" ("ID_GRUPY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_KONTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK"."ID_KONTA_PK" ON "PK"."LOGIN" ("ID_KONTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_SALI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK"."ID_SALI_PK" ON "PK"."SALA" ("ID_SALI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_ZAJECIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK"."ID_ZAJECIE_PK" ON "PK"."ZAJECIE" ("ID_ZAJECIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KONTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK"."KONTO_PK" ON "PK"."KONTO" ("ID_KONTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PUBLIKACJA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK"."PUBLIKACJA_PK" ON "PK"."PUBLIKACJA" ("ID_PUBLIKACJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STATUS_TASKA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK"."STATUS_TASKA_PK" ON "PK"."STATUS_TASKA" ("ID_STATUSU_TASKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TAKS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK"."TAKS_PK" ON "PK"."TASK" ("ID_TASKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TYP_KONTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK"."TYP_KONTA_PK" ON "PK"."TYP_KONTA" ("ID_TYPU_KONTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WAGA_ZADANIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK"."WAGA_ZADANIA_PK" ON "PK"."WAGA_ZADANIA" ("ID_WAGI_ZADANIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ZADANIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK"."ZADANIE_PK" ON "PK"."ZADANIE" ("ID_ZADANIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger KONTO_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "PK"."KONTO_TRG" 
BEFORE INSERT ON KONTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_KONTA IS NULL THEN
      SELECT KONTO_SEQ.NEXTVAL INTO :NEW.ID_KONTA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PK"."KONTO_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTORZY
--------------------------------------------------------

  ALTER TABLE "PK"."AUTORZY" MODIFY ("ID_AUTORA" NOT NULL ENABLE);
  ALTER TABLE "PK"."AUTORZY" MODIFY ("ID_KONTA" NOT NULL ENABLE);
  ALTER TABLE "PK"."AUTORZY" ADD CONSTRAINT "AUTORZY_PK" PRIMARY KEY ("ID_AUTORA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BUDYNEK
--------------------------------------------------------

  ALTER TABLE "PK"."BUDYNEK" MODIFY ("ID_BUDYNKU" NOT NULL ENABLE);
  ALTER TABLE "PK"."BUDYNEK" MODIFY ("NAZWA_BUDYNKU" NOT NULL ENABLE);
  ALTER TABLE "PK"."BUDYNEK" ADD CONSTRAINT "ID_BUDYNKU_PK" PRIMARY KEY ("ID_BUDYNKU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GRUPA_STUDENTOW
--------------------------------------------------------

  ALTER TABLE "PK"."GRUPA_STUDENTOW" MODIFY ("ID_GRUPY" NOT NULL ENABLE);
  ALTER TABLE "PK"."GRUPA_STUDENTOW" MODIFY ("ILOSC_OSOB" NOT NULL ENABLE);
  ALTER TABLE "PK"."GRUPA_STUDENTOW" MODIFY ("SPECJALIZACJA" NOT NULL ENABLE);
  ALTER TABLE "PK"."GRUPA_STUDENTOW" ADD CONSTRAINT "ID_GRUPY_PK" PRIMARY KEY ("ID_GRUPY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KONTO
--------------------------------------------------------

  ALTER TABLE "PK"."KONTO" MODIFY ("ID_KONTA" NOT NULL ENABLE);
  ALTER TABLE "PK"."KONTO" MODIFY ("TYTUL" NOT NULL ENABLE);
  ALTER TABLE "PK"."KONTO" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "PK"."KONTO" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "PK"."KONTO" MODIFY ("ID_TYPU_KONTA" NOT NULL ENABLE);
  ALTER TABLE "PK"."KONTO" MODIFY ("SPECJALIZACJA" NOT NULL ENABLE);
  ALTER TABLE "PK"."KONTO" ADD CONSTRAINT "KONTO_PK" PRIMARY KEY ("ID_KONTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "PK"."LOGIN" MODIFY ("ID_KONTA" NOT NULL ENABLE);
  ALTER TABLE "PK"."LOGIN" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "PK"."LOGIN" MODIFY ("HASLO" NOT NULL ENABLE);
  ALTER TABLE "PK"."LOGIN" ADD CONSTRAINT "ID_KONTA_PK" PRIMARY KEY ("ID_KONTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PUBLIKACJA
--------------------------------------------------------

  ALTER TABLE "PK"."PUBLIKACJA" MODIFY ("ID_PUBLIKACJI" NOT NULL ENABLE);
  ALTER TABLE "PK"."PUBLIKACJA" MODIFY ("ID_AUTORA" NOT NULL ENABLE);
  ALTER TABLE "PK"."PUBLIKACJA" MODIFY ("TYTUL_PUBLIKACJI" NOT NULL ENABLE);
  ALTER TABLE "PK"."PUBLIKACJA" MODIFY ("DATA_PUBLIKACJI" NOT NULL ENABLE);
  ALTER TABLE "PK"."PUBLIKACJA" MODIFY ("ISBN" NOT NULL ENABLE);
  ALTER TABLE "PK"."PUBLIKACJA" MODIFY ("MIESJCE_WYSTAPIENIA" NOT NULL ENABLE);
  ALTER TABLE "PK"."PUBLIKACJA" ADD CONSTRAINT "PUBLIKACJA_PK" PRIMARY KEY ("ID_PUBLIKACJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALA
--------------------------------------------------------

  ALTER TABLE "PK"."SALA" MODIFY ("ID_SALI" NOT NULL ENABLE);
  ALTER TABLE "PK"."SALA" MODIFY ("ID_BUDYNKU" NOT NULL ENABLE);
  ALTER TABLE "PK"."SALA" MODIFY ("NR_SALI" NOT NULL ENABLE);
  ALTER TABLE "PK"."SALA" MODIFY ("TYP_SALI" NOT NULL ENABLE);
  ALTER TABLE "PK"."SALA" MODIFY ("MAX_OS" NOT NULL ENABLE);
  ALTER TABLE "PK"."SALA" MODIFY ("WYPOSAZENIE" NOT NULL ENABLE);
  ALTER TABLE "PK"."SALA" ADD CONSTRAINT "ID_SALI_PK" PRIMARY KEY ("ID_SALI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATUS_TASKA
--------------------------------------------------------

  ALTER TABLE "PK"."STATUS_TASKA" MODIFY ("ID_STATUSU_TASKA" NOT NULL ENABLE);
  ALTER TABLE "PK"."STATUS_TASKA" MODIFY ("NAZWA_STATUSU" NOT NULL ENABLE);
  ALTER TABLE "PK"."STATUS_TASKA" ADD CONSTRAINT "STATUS_TASKA_PK" PRIMARY KEY ("ID_STATUSU_TASKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TASK
--------------------------------------------------------

  ALTER TABLE "PK"."TASK" MODIFY ("ID_TASKA" NOT NULL ENABLE);
  ALTER TABLE "PK"."TASK" MODIFY ("DATA_UTWORZENIA" NOT NULL ENABLE);
  ALTER TABLE "PK"."TASK" MODIFY ("CZAS_REALIZACJI" NOT NULL ENABLE);
  ALTER TABLE "PK"."TASK" MODIFY ("TYTUL_TASKA" NOT NULL ENABLE);
  ALTER TABLE "PK"."TASK" MODIFY ("ID_STATUSU_TASKA" NOT NULL ENABLE);
  ALTER TABLE "PK"."TASK" ADD CONSTRAINT "TAKS_PK" PRIMARY KEY ("ID_TASKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TYP_KONTA
--------------------------------------------------------

  ALTER TABLE "PK"."TYP_KONTA" MODIFY ("ID_TYPU_KONTA" NOT NULL ENABLE);
  ALTER TABLE "PK"."TYP_KONTA" MODIFY ("NAZWA_TYPU_KONTA" NOT NULL ENABLE);
  ALTER TABLE "PK"."TYP_KONTA" ADD CONSTRAINT "TYP_KONTA_PK" PRIMARY KEY ("ID_TYPU_KONTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WAGA_ZADANIA
--------------------------------------------------------

  ALTER TABLE "PK"."WAGA_ZADANIA" MODIFY ("ID_WAGI_ZADANIA" NOT NULL ENABLE);
  ALTER TABLE "PK"."WAGA_ZADANIA" MODIFY ("WAGA" NOT NULL ENABLE);
  ALTER TABLE "PK"."WAGA_ZADANIA" ADD CONSTRAINT "WAGA_ZADANIA_PK" PRIMARY KEY ("ID_WAGI_ZADANIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZADANIE
--------------------------------------------------------

  ALTER TABLE "PK"."ZADANIE" MODIFY ("ID_ZADANIA" NOT NULL ENABLE);
  ALTER TABLE "PK"."ZADANIE" MODIFY ("ID_KONTA" NOT NULL ENABLE);
  ALTER TABLE "PK"."ZADANIE" MODIFY ("ID_TASKA" NOT NULL ENABLE);
  ALTER TABLE "PK"."ZADANIE" ADD CONSTRAINT "ZADANIE_PK" PRIMARY KEY ("ID_ZADANIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZAJECIE
--------------------------------------------------------

  ALTER TABLE "PK"."ZAJECIE" MODIFY ("ID_ZAJECIA" NOT NULL ENABLE);
  ALTER TABLE "PK"."ZAJECIE" MODIFY ("ID_GRUPY" NOT NULL ENABLE);
  ALTER TABLE "PK"."ZAJECIE" MODIFY ("ID_KONTA" NOT NULL ENABLE);
  ALTER TABLE "PK"."ZAJECIE" MODIFY ("ID_SALI" NOT NULL ENABLE);
  ALTER TABLE "PK"."ZAJECIE" MODIFY ("SPECJALIZACJA" NOT NULL ENABLE);
  ALTER TABLE "PK"."ZAJECIE" MODIFY ("LICZBA_GODZIN" NOT NULL ENABLE);
  ALTER TABLE "PK"."ZAJECIE" MODIFY ("DZIEN_TYGODNIA" NOT NULL ENABLE);
  ALTER TABLE "PK"."ZAJECIE" MODIFY ("GODZINA_ROZPOCZECIA" NOT NULL ENABLE);
  ALTER TABLE "PK"."ZAJECIE" ADD CONSTRAINT "ID_ZAJECIE_PK" PRIMARY KEY ("ID_ZAJECIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PK"."ZAJECIE" MODIFY ("WYPOSAZENIE" NOT NULL ENABLE);
